name: soriana_tracker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^3.5.0
  copy_with_extension: ^4.0.3
  cupertino_icons: ^1.0.2
  equatable: null
  eva_icons_flutter: ^3.1.0
  firebase_auth: ^3.11.0
  firebase_core: ^1.24.0
  flow_builder: null
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_staggered_grid_view: ^0.4.1

  flutter_svg: ^1.1.5
  get: ^4.6.5
  google_sign_in: ^5.4.2
  intl: ^0.17.0
  percent_indicator: ^4.2.2

dev_dependencies:
  build_runner: ^2.1.7
  copy_with_extension_gen: ^4.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/roboto.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
