// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt_F2GKEwjhbheVc6yWfo0fzc2ZziusxM',
    appId: '1:43153164075:web:df3e338529a52f7640276e',
    messagingSenderId: '43153164075',
    projectId: 'soriana-tracker',
    authDomain: 'soriana-tracker.firebaseapp.com',
    storageBucket: 'soriana-tracker.appspot.com',
    measurementId: 'G-XQX1GE15YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa09g3hOPKRLmSbgZPMVeTjLQwrRhWb_M',
    appId: '1:43153164075:android:41dacc6c6306c4ad40276e',
    messagingSenderId: '43153164075',
    projectId: 'soriana-tracker',
    storageBucket: 'soriana-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmAxQM6b4gqtaahk6_e5ZSMcTY0aJdwUk',
    appId: '1:43153164075:ios:5256a599d3ded54040276e',
    messagingSenderId: '43153164075',
    projectId: 'soriana-tracker',
    storageBucket: 'soriana-tracker.appspot.com',
    androidClientId: '43153164075-6pv39oeqp9aoaau9fjcm7k69p725712q.apps.googleusercontent.com',
    iosClientId: '43153164075-nqcmqa4sbaqnt86tilcl12rt5tdeipkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.sorianaTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmAxQM6b4gqtaahk6_e5ZSMcTY0aJdwUk',
    appId: '1:43153164075:ios:5256a599d3ded54040276e',
    messagingSenderId: '43153164075',
    projectId: 'soriana-tracker',
    storageBucket: 'soriana-tracker.appspot.com',
    androidClientId: '43153164075-6pv39oeqp9aoaau9fjcm7k69p725712q.apps.googleusercontent.com',
    iosClientId: '43153164075-nqcmqa4sbaqnt86tilcl12rt5tdeipkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.sorianaTracker',
  );
}
